import React from 'react';
import Layout from '../../layout';

const ListPage = () => {
    const Table = () => {
        const data = [
          { postCode: 'CV1', name: 'Daniel Pelka', summary: 'Daniel Pelka was a four-year-old boy who migrated to the UK from Poland...', generatedBy: 'Social Worker 1', status: 'Red' },
          { postCode: 'BD5', name: 'Star Hobson', summary: 'Star Hobson was an inquisitive toddler who loved to listen to music and...', generatedBy: 'Social Worker 2', status: 'Red' },
          { postCode: 'BD7', name: 'Arthur Labinjo-Hughes', summary: 'Arthur Labinjo-Hughes was a little boy who loved playing cricket and...', generatedBy: 'Social Worker 3', status: 'Red' },
          // Add more data as needed
        ];
      
        return (
          <div className="table-container">
            <div className="table-header">
              <span>All</span>
              <span>High Priority</span>
            </div>
            <table className="data-table">
              <thead>
                <tr>
                  <th>Post code</th>
                  <th>Name of the Child</th>
                  <th>Case Quick Summary</th>
                  <th>Generated by</th>
                  <th>Status</th>
                </tr>
              </thead>
              <tbody>
                {data.map((row, index) => (
                  <tr key={index}>
                    <td>{row.postCode}</td>
                    <td>{row.name}</td>
                    <td>{row.summary}</td>
                    <td>{row.generatedBy}</td>
                    <td>{row.status}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        );
      };
    return (
        <div>
            <Layout><Table/></Layout>
        </div>
    );
}

export default ListPage;
