import React, { useState } from "react";
import Layout from "../../layout";
import styles from "../listpage/ListPage.module.css";
import { useNavigate } from 'react-router-dom';

const ListPage = () => {
    const navigate = useNavigate();
  const goTolist = () => {
    navigate('/detail');
  };
  const [activeTab, setActiveTab] = useState("all");

  const handleTabClick = (tab) => {
    setActiveTab(tab);
  };
  const Table = () => {
   

    return (
     
      <div className={` ${styles.main}`}>
        <div className={styles.TabDiv}>
          <div
            className={`${styles.tab} ${
              activeTab === "all" ? styles.activeAll : styles.inactive
            }`}
            onClick={() => handleTabClick("all")}
          >
            <h1>All</h1>
            <h2>18</h2>
          </div>
          <div
            className={`${styles.tab} ${
              activeTab === "highPriority"
                ? styles.activeHighPriority
                : styles.inactive
            }`}
            onClick={() => handleTabClick("highPriority")}
          >
            <h1>High Priority</h1>
          </div>
        </div>

        {activeTab === "all" ? (
          <div className={`table-responsive ${styles.tabList}`}>
            <table className={`table ${styles.Table}`}>
              <thead className="thead-dark">
                <tr className={styles.theadTitle}>
                  <th scope="col">Post code</th>
                  <th scope="col">Name of the Child</th>
                  <th scope="col">Case Quick Summary</th>
                  <th scope="col">Generated by</th>
                  <th scope="col">Status</th>
                </tr>
              </thead>
              <tbody>
                <tr onClick={goTolist} className={styles.TRhover}>
                  <td>CV1</td>
                  <td className={styles.childName1}>
                    <span>DP</span> Daniel Pelka
                  </td>
                  <td>
                    Daniel Pelka was a four-year-old boy who migrated to the UK
                    from Poland...
                  </td>
                  <td>Social Worker 1</td>
                  <td className={styles.statusDiv}>
                    <div className={styles.statusRed}></div> Red
                  </td>
                </tr>
                <tr onClick={goTolist} className={styles.TRhover}>
                  <td>BD5</td>
                  <td className={styles.childName2}>
                    <span>SH</span> Star Hobson
                  </td>
                  <td>
                    Star Hobson was an inquisitive toddler who loved to listen
                    to music and...
                  </td>
                  <td>Social Worker 2</td>
                  <td className={styles.statusDiv}>
                    <div className={styles.statusRed}></div> Red
                  </td>
                </tr>
                <tr onClick={goTolist} className={styles.TRhover}>
                  <td>BD7</td>
                  <td className={styles.childName3}>
                    <span>AL</span> Arthur Labinjo-Hughes
                  </td>
                  <td>
                    Arthur Labinjo-Hughes was a little boy who loved playing
                    cricket and...
                  </td>
                  <td>Social Worker 3</td>
                  <td className={styles.statusDiv}>
                    <div className={styles.statusRed}></div> Red
                  </td>
                </tr>
                <tr onClick={goTolist} className={styles.TRhover}>
                  <td>SW18</td>
                  <td className={styles.childName4}>
                    <span>L</span> Lloyd
                  </td>
                  <td>
                    Arthur Labinjo-Hughes was a little boy who loved playing
                    cricket and...
                  </td>
                  <td>Social Worker 3</td>
                  <td className={styles.statusDiv}>
                    <div className={styles.statusRed}></div> Red
                  </td>
                </tr>
                <tr onClick={goTolist} className={styles.TRhover}>
                  <td>CV1</td>
                  <td className={styles.childName1}>
                    <span>DP</span> Daniel Pelka
                  </td>
                  <td>
                    Daniel Pelka was a four-year-old boy who migrated to the UK
                    from Poland...
                  </td>
                  <td>Social Worker 1</td>
                  <td className={styles.statusDiv}>
                    <div className={styles.statusOrange}></div> Orange
                  </td>
                </tr>
                <tr onClick={goTolist} className={styles.TRhover}>
                  <td>BD5</td>
                  <td className={styles.childName2}>
                    <span>SH</span> Star Hobson
                  </td>
                  <td>
                    Star Hobson was an inquisitive toddler who loved to listen
                    to music and...
                  </td>
                  <td>Social Worker 2</td>
                  <td className={styles.statusDiv}>
                    <div className={styles.statusRed}></div> Red
                  </td>
                </tr>
                <tr onClick={goTolist} className={styles.TRhover}>
                  <td>BD7</td>
                  <td className={styles.childName3}>
                    <span>AL</span> Arthur Labinjo-Hughes
                  </td>
                  <td>
                    Arthur Labinjo-Hughes was a little boy who loved playing
                    cricket and...
                  </td>
                  <td>Social Worker 3</td>
                  <td className={styles.statusDiv}>
                    <div className={styles.statusRed}></div> Red
                  </td>
                </tr>
                <tr onClick={goTolist} className={styles.TRhover}>
                  <td>SW18</td>
                  <td className={styles.childName4}>
                    <span>L</span> Lloyd
                  </td>
                  <td>
                    Arthur Labinjo-Hughes was a little boy who loved playing
                    cricket and...
                  </td>
                  <td>Social Worker 3</td>
                  <td className={styles.statusDiv}>
                    <div className={styles.statusGreen}></div> Green
                  </td>
                </tr>
                <tr onClick={goTolist} className={styles.TRhover}>
                  <td>CV1</td>
                  <td className={styles.childName1}>
                    <span>DP</span> Daniel Pelka
                  </td>
                  <td>
                    Daniel Pelka was a four-year-old boy who migrated to the UK
                    from Poland...
                  </td>
                  <td>Social Worker 1</td>
                  <td className={styles.statusDiv}>
                    <div className={styles.statusRed}></div> Red
                  </td>
                </tr>
                <tr onClick={goTolist} className={styles.TRhover}>
                  <td>BD5</td>
                  <td className={styles.childName2}>
                    <span>SH</span> Star Hobson
                  </td>
                  <td>
                    Star Hobson was an inquisitive toddler who loved to listen
                    to music and...
                  </td>
                  <td>Social Worker 2</td>
                  <td className={styles.statusDiv}>
                    <div className={styles.statusOrange}></div> Orange
                  </td>
                </tr>
                <tr onClick={goTolist} className={styles.TRhover}>
                  <td>BD7</td>
                  <td className={styles.childName3}>
                    <span>AL</span> Arthur Labinjo-Hughes
                  </td>
                  <td>
                    Arthur Labinjo-Hughes was a little boy who loved playing
                    cricket and...
                  </td>
                  <td>Social Worker 3</td>
                  <td className={styles.statusDiv}>
                    <div className={styles.statusRed}></div> Red
                  </td>
                </tr>
                <tr onClick={goTolist} className={styles.TRhover}>
                  <td>SW18</td>
                  <td className={styles.childName4}>
                    <span>L</span> Lloyd
                  </td>
                  <td>
                    Arthur Labinjo-Hughes was a little boy who loved playing
                    cricket and...
                  </td>
                  <td>Social Worker 3</td>
                  <td className={styles.statusDiv}>
                    <div className={styles.statusGreen}></div> Green
                  </td>
                </tr>
              </tbody>
            </table>
          </div>
        ) : (
          <div className={styles.comingSoon}>
            <h2>Coming Soon</h2>
          </div>
        )}
      </div>
    );
  };
  return (
    <div>
      <Layout>
        <Table />
      </Layout>
    </div>
  );
};

export default ListPage;
